version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - run: go test -v ./...
  release:
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  release:
    jobs:
      - test
      - release:
          requires:
            - test
          context: release
          filters:
            tags:
              only: /^v.*/
