version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - run: go test -v ./...
  release:
    docker:
      - image: circleci/golang:1
    requires:
      - test
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
